// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: protos/event.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventService_GetEvents_FullMethodName          = "/event.EventService/GetEvents"
	EventService_SubmitCodeSolution_FullMethodName = "/event.EventService/SubmitCodeSolution"
	EventService_GetUserSubmissions_FullMethodName = "/event.EventService/GetUserSubmissions"
	EventService_GetCodeProblems_FullMethodName    = "/event.EventService/GetCodeProblems"
)

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventServiceClient interface {
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error)
	SubmitCodeSolution(ctx context.Context, in *SubmitCodeSolutionRequest, opts ...grpc.CallOption) (*SubmitCodeSolutionResponse, error)
	GetUserSubmissions(ctx context.Context, in *GetUserSubmissionsRequest, opts ...grpc.CallOption) (*GetUserSubmissionsResponse, error)
	GetCodeProblems(ctx context.Context, in *GetCodeProblemCriteria, opts ...grpc.CallOption) (*CodeProblemResponse, error)
}

type eventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventsResponse)
	err := c.cc.Invoke(ctx, EventService_GetEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) SubmitCodeSolution(ctx context.Context, in *SubmitCodeSolutionRequest, opts ...grpc.CallOption) (*SubmitCodeSolutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitCodeSolutionResponse)
	err := c.cc.Invoke(ctx, EventService_SubmitCodeSolution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetUserSubmissions(ctx context.Context, in *GetUserSubmissionsRequest, opts ...grpc.CallOption) (*GetUserSubmissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserSubmissionsResponse)
	err := c.cc.Invoke(ctx, EventService_GetUserSubmissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetCodeProblems(ctx context.Context, in *GetCodeProblemCriteria, opts ...grpc.CallOption) (*CodeProblemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CodeProblemResponse)
	err := c.cc.Invoke(ctx, EventService_GetCodeProblems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
// All implementations must embed UnimplementedEventServiceServer
// for forward compatibility.
type EventServiceServer interface {
	GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error)
	SubmitCodeSolution(context.Context, *SubmitCodeSolutionRequest) (*SubmitCodeSolutionResponse, error)
	GetUserSubmissions(context.Context, *GetUserSubmissionsRequest) (*GetUserSubmissionsResponse, error)
	GetCodeProblems(context.Context, *GetCodeProblemCriteria) (*CodeProblemResponse, error)
	mustEmbedUnimplementedEventServiceServer()
}

// UnimplementedEventServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventServiceServer struct{}

func (UnimplementedEventServiceServer) GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}
func (UnimplementedEventServiceServer) SubmitCodeSolution(context.Context, *SubmitCodeSolutionRequest) (*SubmitCodeSolutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitCodeSolution not implemented")
}
func (UnimplementedEventServiceServer) GetUserSubmissions(context.Context, *GetUserSubmissionsRequest) (*GetUserSubmissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserSubmissions not implemented")
}
func (UnimplementedEventServiceServer) GetCodeProblems(context.Context, *GetCodeProblemCriteria) (*CodeProblemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCodeProblems not implemented")
}
func (UnimplementedEventServiceServer) mustEmbedUnimplementedEventServiceServer() {}
func (UnimplementedEventServiceServer) testEmbeddedByValue()                      {}

// UnsafeEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventServiceServer will
// result in compilation errors.
type UnsafeEventServiceServer interface {
	mustEmbedUnimplementedEventServiceServer()
}

func RegisterEventServiceServer(s grpc.ServiceRegistrar, srv EventServiceServer) {
	// If the following call pancis, it indicates UnimplementedEventServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventService_ServiceDesc, srv)
}

func _EventService_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEvents(ctx, req.(*GetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_SubmitCodeSolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitCodeSolutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).SubmitCodeSolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_SubmitCodeSolution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).SubmitCodeSolution(ctx, req.(*SubmitCodeSolutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetUserSubmissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserSubmissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetUserSubmissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetUserSubmissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetUserSubmissions(ctx, req.(*GetUserSubmissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetCodeProblems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCodeProblemCriteria)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetCodeProblems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetCodeProblems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetCodeProblems(ctx, req.(*GetCodeProblemCriteria))
	}
	return interceptor(ctx, in, info, handler)
}

// EventService_ServiceDesc is the grpc.ServiceDesc for EventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "event.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEvents",
			Handler:    _EventService_GetEvents_Handler,
		},
		{
			MethodName: "SubmitCodeSolution",
			Handler:    _EventService_SubmitCodeSolution_Handler,
		},
		{
			MethodName: "GetUserSubmissions",
			Handler:    _EventService_GetUserSubmissions_Handler,
		},
		{
			MethodName: "GetCodeProblems",
			Handler:    _EventService_GetCodeProblems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/event.proto",
}
