// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: user.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserProfilesService_GetByAuthId_FullMethodName     = "/user.v1.UserProfilesService/GetByAuthId"
	UserProfilesService_UpdateMyProfile_FullMethodName = "/user.v1.UserProfilesService/UpdateMyProfile"
	UserProfilesService_LogNewUser_FullMethodName      = "/user.v1.UserProfilesService/LogNewUser"
	UserProfilesService_GetAll_FullMethodName          = "/user.v1.UserProfilesService/GetAll"
)

// UserProfilesServiceClient is the client API for UserProfilesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserProfilesServiceClient interface {
	GetByAuthId(ctx context.Context, in *GetUserProfileByAuthIdRequest, opts ...grpc.CallOption) (*UserProfile, error)
	UpdateMyProfile(ctx context.Context, in *UpdateMyProfileRequest, opts ...grpc.CallOption) (*UserProfile, error)
	LogNewUser(ctx context.Context, in *LogNewUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetAll(ctx context.Context, in *GetAllUserProfilesRequest, opts ...grpc.CallOption) (*UserProfileList, error)
}

type userProfilesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserProfilesServiceClient(cc grpc.ClientConnInterface) UserProfilesServiceClient {
	return &userProfilesServiceClient{cc}
}

func (c *userProfilesServiceClient) GetByAuthId(ctx context.Context, in *GetUserProfileByAuthIdRequest, opts ...grpc.CallOption) (*UserProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProfile)
	err := c.cc.Invoke(ctx, UserProfilesService_GetByAuthId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfilesServiceClient) UpdateMyProfile(ctx context.Context, in *UpdateMyProfileRequest, opts ...grpc.CallOption) (*UserProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProfile)
	err := c.cc.Invoke(ctx, UserProfilesService_UpdateMyProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfilesServiceClient) LogNewUser(ctx context.Context, in *LogNewUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserProfilesService_LogNewUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfilesServiceClient) GetAll(ctx context.Context, in *GetAllUserProfilesRequest, opts ...grpc.CallOption) (*UserProfileList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProfileList)
	err := c.cc.Invoke(ctx, UserProfilesService_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserProfilesServiceServer is the server API for UserProfilesService service.
// All implementations must embed UnimplementedUserProfilesServiceServer
// for forward compatibility.
type UserProfilesServiceServer interface {
	GetByAuthId(context.Context, *GetUserProfileByAuthIdRequest) (*UserProfile, error)
	UpdateMyProfile(context.Context, *UpdateMyProfileRequest) (*UserProfile, error)
	LogNewUser(context.Context, *LogNewUserRequest) (*emptypb.Empty, error)
	GetAll(context.Context, *GetAllUserProfilesRequest) (*UserProfileList, error)
	mustEmbedUnimplementedUserProfilesServiceServer()
}

// UnimplementedUserProfilesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserProfilesServiceServer struct{}

func (UnimplementedUserProfilesServiceServer) GetByAuthId(context.Context, *GetUserProfileByAuthIdRequest) (*UserProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByAuthId not implemented")
}
func (UnimplementedUserProfilesServiceServer) UpdateMyProfile(context.Context, *UpdateMyProfileRequest) (*UserProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMyProfile not implemented")
}
func (UnimplementedUserProfilesServiceServer) LogNewUser(context.Context, *LogNewUserRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogNewUser not implemented")
}
func (UnimplementedUserProfilesServiceServer) GetAll(context.Context, *GetAllUserProfilesRequest) (*UserProfileList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedUserProfilesServiceServer) mustEmbedUnimplementedUserProfilesServiceServer() {}
func (UnimplementedUserProfilesServiceServer) testEmbeddedByValue()                             {}

// UnsafeUserProfilesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserProfilesServiceServer will
// result in compilation errors.
type UnsafeUserProfilesServiceServer interface {
	mustEmbedUnimplementedUserProfilesServiceServer()
}

func RegisterUserProfilesServiceServer(s grpc.ServiceRegistrar, srv UserProfilesServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserProfilesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserProfilesService_ServiceDesc, srv)
}

func _UserProfilesService_GetByAuthId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserProfileByAuthIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfilesServiceServer).GetByAuthId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProfilesService_GetByAuthId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfilesServiceServer).GetByAuthId(ctx, req.(*GetUserProfileByAuthIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProfilesService_UpdateMyProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMyProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfilesServiceServer).UpdateMyProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProfilesService_UpdateMyProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfilesServiceServer).UpdateMyProfile(ctx, req.(*UpdateMyProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProfilesService_LogNewUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogNewUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfilesServiceServer).LogNewUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProfilesService_LogNewUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfilesServiceServer).LogNewUser(ctx, req.(*LogNewUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProfilesService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllUserProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfilesServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProfilesService_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfilesServiceServer).GetAll(ctx, req.(*GetAllUserProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserProfilesService_ServiceDesc is the grpc.ServiceDesc for UserProfilesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserProfilesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.v1.UserProfilesService",
	HandlerType: (*UserProfilesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByAuthId",
			Handler:    _UserProfilesService_GetByAuthId_Handler,
		},
		{
			MethodName: "UpdateMyProfile",
			Handler:    _UserProfilesService_UpdateMyProfile_Handler,
		},
		{
			MethodName: "LogNewUser",
			Handler:    _UserProfilesService_LogNewUser_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _UserProfilesService_GetAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

const (
	UserContextService_GetByAuthId_FullMethodName = "/user.v1.UserContextService/GetByAuthId"
)

// UserContextServiceClient is the client API for UserContextService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserContextServiceClient interface {
	GetByAuthId(ctx context.Context, in *GetUserContextByAuthIdRequest, opts ...grpc.CallOption) (*UserContext, error)
}

type userContextServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserContextServiceClient(cc grpc.ClientConnInterface) UserContextServiceClient {
	return &userContextServiceClient{cc}
}

func (c *userContextServiceClient) GetByAuthId(ctx context.Context, in *GetUserContextByAuthIdRequest, opts ...grpc.CallOption) (*UserContext, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserContext)
	err := c.cc.Invoke(ctx, UserContextService_GetByAuthId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserContextServiceServer is the server API for UserContextService service.
// All implementations must embed UnimplementedUserContextServiceServer
// for forward compatibility.
type UserContextServiceServer interface {
	GetByAuthId(context.Context, *GetUserContextByAuthIdRequest) (*UserContext, error)
	mustEmbedUnimplementedUserContextServiceServer()
}

// UnimplementedUserContextServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserContextServiceServer struct{}

func (UnimplementedUserContextServiceServer) GetByAuthId(context.Context, *GetUserContextByAuthIdRequest) (*UserContext, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByAuthId not implemented")
}
func (UnimplementedUserContextServiceServer) mustEmbedUnimplementedUserContextServiceServer() {}
func (UnimplementedUserContextServiceServer) testEmbeddedByValue()                            {}

// UnsafeUserContextServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserContextServiceServer will
// result in compilation errors.
type UnsafeUserContextServiceServer interface {
	mustEmbedUnimplementedUserContextServiceServer()
}

func RegisterUserContextServiceServer(s grpc.ServiceRegistrar, srv UserContextServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserContextServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserContextService_ServiceDesc, srv)
}

func _UserContextService_GetByAuthId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserContextByAuthIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserContextServiceServer).GetByAuthId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserContextService_GetByAuthId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserContextServiceServer).GetByAuthId(ctx, req.(*GetUserContextByAuthIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserContextService_ServiceDesc is the grpc.ServiceDesc for UserContextService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserContextService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.v1.UserContextService",
	HandlerType: (*UserContextServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByAuthId",
			Handler:    _UserContextService_GetByAuthId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

const (
	AchievementsService_GetAll_FullMethodName          = "/user.v1.AchievementsService/GetAll"
	AchievementsService_Create_FullMethodName          = "/user.v1.AchievementsService/Create"
	AchievementsService_Update_FullMethodName          = "/user.v1.AchievementsService/Update"
	AchievementsService_Delete_FullMethodName          = "/user.v1.AchievementsService/Delete"
	AchievementsService_AwardToUser_FullMethodName     = "/user.v1.AchievementsService/AwardToUser"
	AchievementsService_RevokeFromUser_FullMethodName  = "/user.v1.AchievementsService/RevokeFromUser"
	AchievementsService_GetByAuthUserId_FullMethodName = "/user.v1.AchievementsService/GetByAuthUserId"
)

// AchievementsServiceClient is the client API for AchievementsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AchievementsServiceClient interface {
	GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*AchievementList, error)
	Create(ctx context.Context, in *CreateAchievementRequest, opts ...grpc.CallOption) (*Achievement, error)
	Update(ctx context.Context, in *UpdateAchievementRequest, opts ...grpc.CallOption) (*Achievement, error)
	Delete(ctx context.Context, in *DeleteAchievementRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AwardToUser(ctx context.Context, in *AwardAchievementToUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RevokeFromUser(ctx context.Context, in *RevokeAchievementFromUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetByAuthUserId(ctx context.Context, in *GetUserAchievementsByAuthUserIdRequest, opts ...grpc.CallOption) (*UserAchievementList, error)
}

type achievementsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAchievementsServiceClient(cc grpc.ClientConnInterface) AchievementsServiceClient {
	return &achievementsServiceClient{cc}
}

func (c *achievementsServiceClient) GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*AchievementList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AchievementList)
	err := c.cc.Invoke(ctx, AchievementsService_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *achievementsServiceClient) Create(ctx context.Context, in *CreateAchievementRequest, opts ...grpc.CallOption) (*Achievement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Achievement)
	err := c.cc.Invoke(ctx, AchievementsService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *achievementsServiceClient) Update(ctx context.Context, in *UpdateAchievementRequest, opts ...grpc.CallOption) (*Achievement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Achievement)
	err := c.cc.Invoke(ctx, AchievementsService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *achievementsServiceClient) Delete(ctx context.Context, in *DeleteAchievementRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AchievementsService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *achievementsServiceClient) AwardToUser(ctx context.Context, in *AwardAchievementToUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AchievementsService_AwardToUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *achievementsServiceClient) RevokeFromUser(ctx context.Context, in *RevokeAchievementFromUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AchievementsService_RevokeFromUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *achievementsServiceClient) GetByAuthUserId(ctx context.Context, in *GetUserAchievementsByAuthUserIdRequest, opts ...grpc.CallOption) (*UserAchievementList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserAchievementList)
	err := c.cc.Invoke(ctx, AchievementsService_GetByAuthUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AchievementsServiceServer is the server API for AchievementsService service.
// All implementations must embed UnimplementedAchievementsServiceServer
// for forward compatibility.
type AchievementsServiceServer interface {
	GetAll(context.Context, *GetAllRequest) (*AchievementList, error)
	Create(context.Context, *CreateAchievementRequest) (*Achievement, error)
	Update(context.Context, *UpdateAchievementRequest) (*Achievement, error)
	Delete(context.Context, *DeleteAchievementRequest) (*emptypb.Empty, error)
	AwardToUser(context.Context, *AwardAchievementToUserRequest) (*emptypb.Empty, error)
	RevokeFromUser(context.Context, *RevokeAchievementFromUserRequest) (*emptypb.Empty, error)
	GetByAuthUserId(context.Context, *GetUserAchievementsByAuthUserIdRequest) (*UserAchievementList, error)
	mustEmbedUnimplementedAchievementsServiceServer()
}

// UnimplementedAchievementsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAchievementsServiceServer struct{}

func (UnimplementedAchievementsServiceServer) GetAll(context.Context, *GetAllRequest) (*AchievementList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedAchievementsServiceServer) Create(context.Context, *CreateAchievementRequest) (*Achievement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedAchievementsServiceServer) Update(context.Context, *UpdateAchievementRequest) (*Achievement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedAchievementsServiceServer) Delete(context.Context, *DeleteAchievementRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAchievementsServiceServer) AwardToUser(context.Context, *AwardAchievementToUserRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AwardToUser not implemented")
}
func (UnimplementedAchievementsServiceServer) RevokeFromUser(context.Context, *RevokeAchievementFromUserRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeFromUser not implemented")
}
func (UnimplementedAchievementsServiceServer) GetByAuthUserId(context.Context, *GetUserAchievementsByAuthUserIdRequest) (*UserAchievementList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByAuthUserId not implemented")
}
func (UnimplementedAchievementsServiceServer) mustEmbedUnimplementedAchievementsServiceServer() {}
func (UnimplementedAchievementsServiceServer) testEmbeddedByValue()                             {}

// UnsafeAchievementsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AchievementsServiceServer will
// result in compilation errors.
type UnsafeAchievementsServiceServer interface {
	mustEmbedUnimplementedAchievementsServiceServer()
}

func RegisterAchievementsServiceServer(s grpc.ServiceRegistrar, srv AchievementsServiceServer) {
	// If the following call pancis, it indicates UnimplementedAchievementsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AchievementsService_ServiceDesc, srv)
}

func _AchievementsService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AchievementsServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AchievementsService_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AchievementsServiceServer).GetAll(ctx, req.(*GetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AchievementsService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAchievementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AchievementsServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AchievementsService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AchievementsServiceServer).Create(ctx, req.(*CreateAchievementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AchievementsService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAchievementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AchievementsServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AchievementsService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AchievementsServiceServer).Update(ctx, req.(*UpdateAchievementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AchievementsService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAchievementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AchievementsServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AchievementsService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AchievementsServiceServer).Delete(ctx, req.(*DeleteAchievementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AchievementsService_AwardToUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AwardAchievementToUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AchievementsServiceServer).AwardToUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AchievementsService_AwardToUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AchievementsServiceServer).AwardToUser(ctx, req.(*AwardAchievementToUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AchievementsService_RevokeFromUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeAchievementFromUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AchievementsServiceServer).RevokeFromUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AchievementsService_RevokeFromUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AchievementsServiceServer).RevokeFromUser(ctx, req.(*RevokeAchievementFromUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AchievementsService_GetByAuthUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAchievementsByAuthUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AchievementsServiceServer).GetByAuthUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AchievementsService_GetByAuthUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AchievementsServiceServer).GetByAuthUserId(ctx, req.(*GetUserAchievementsByAuthUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AchievementsService_ServiceDesc is the grpc.ServiceDesc for AchievementsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AchievementsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.v1.AchievementsService",
	HandlerType: (*AchievementsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAll",
			Handler:    _AchievementsService_GetAll_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _AchievementsService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AchievementsService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AchievementsService_Delete_Handler,
		},
		{
			MethodName: "AwardToUser",
			Handler:    _AchievementsService_AwardToUser_Handler,
		},
		{
			MethodName: "RevokeFromUser",
			Handler:    _AchievementsService_RevokeFromUser_Handler,
		},
		{
			MethodName: "GetByAuthUserId",
			Handler:    _AchievementsService_GetByAuthUserId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

const (
	GuildsService_GetGuildById_FullMethodName      = "/user.v1.GuildsService/GetGuildById"
	GuildsService_GetAllGuilds_FullMethodName      = "/user.v1.GuildsService/GetAllGuilds"
	GuildsService_GetInvitations_FullMethodName    = "/user.v1.GuildsService/GetInvitations"
	GuildsService_GetJoinRequests_FullMethodName   = "/user.v1.GuildsService/GetJoinRequests"
	GuildsService_GetMemberRoles_FullMethodName    = "/user.v1.GuildsService/GetMemberRoles"
	GuildsService_GetMyGuild_FullMethodName        = "/user.v1.GuildsService/GetMyGuild"
	GuildsService_GetMyJoinRequests_FullMethodName = "/user.v1.GuildsService/GetMyJoinRequests"
)

// GuildsServiceClient is the client API for GuildsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GuildsServiceClient interface {
	GetGuildById(ctx context.Context, in *GetGuildByIdRequest, opts ...grpc.CallOption) (*Guild, error)
	GetAllGuilds(ctx context.Context, in *GetAllGuildsRequest, opts ...grpc.CallOption) (*GuildList, error)
	GetInvitations(ctx context.Context, in *GetGuildInvitationsRequest, opts ...grpc.CallOption) (*GuildInvitationList, error)
	GetJoinRequests(ctx context.Context, in *GetGuildJoinRequestsRequest, opts ...grpc.CallOption) (*GuildJoinRequestList, error)
	GetMemberRoles(ctx context.Context, in *GetGuildMemberRolesRequest, opts ...grpc.CallOption) (*GuildMemberRoleList, error)
	GetMyGuild(ctx context.Context, in *GetMyGuildRequest, opts ...grpc.CallOption) (*Guild, error)
	GetMyJoinRequests(ctx context.Context, in *GetMyJoinRequestsRequest, opts ...grpc.CallOption) (*GuildJoinRequestList, error)
}

type guildsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGuildsServiceClient(cc grpc.ClientConnInterface) GuildsServiceClient {
	return &guildsServiceClient{cc}
}

func (c *guildsServiceClient) GetGuildById(ctx context.Context, in *GetGuildByIdRequest, opts ...grpc.CallOption) (*Guild, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Guild)
	err := c.cc.Invoke(ctx, GuildsService_GetGuildById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildsServiceClient) GetAllGuilds(ctx context.Context, in *GetAllGuildsRequest, opts ...grpc.CallOption) (*GuildList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuildList)
	err := c.cc.Invoke(ctx, GuildsService_GetAllGuilds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildsServiceClient) GetInvitations(ctx context.Context, in *GetGuildInvitationsRequest, opts ...grpc.CallOption) (*GuildInvitationList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuildInvitationList)
	err := c.cc.Invoke(ctx, GuildsService_GetInvitations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildsServiceClient) GetJoinRequests(ctx context.Context, in *GetGuildJoinRequestsRequest, opts ...grpc.CallOption) (*GuildJoinRequestList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuildJoinRequestList)
	err := c.cc.Invoke(ctx, GuildsService_GetJoinRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildsServiceClient) GetMemberRoles(ctx context.Context, in *GetGuildMemberRolesRequest, opts ...grpc.CallOption) (*GuildMemberRoleList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuildMemberRoleList)
	err := c.cc.Invoke(ctx, GuildsService_GetMemberRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildsServiceClient) GetMyGuild(ctx context.Context, in *GetMyGuildRequest, opts ...grpc.CallOption) (*Guild, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Guild)
	err := c.cc.Invoke(ctx, GuildsService_GetMyGuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildsServiceClient) GetMyJoinRequests(ctx context.Context, in *GetMyJoinRequestsRequest, opts ...grpc.CallOption) (*GuildJoinRequestList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuildJoinRequestList)
	err := c.cc.Invoke(ctx, GuildsService_GetMyJoinRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuildsServiceServer is the server API for GuildsService service.
// All implementations must embed UnimplementedGuildsServiceServer
// for forward compatibility.
type GuildsServiceServer interface {
	GetGuildById(context.Context, *GetGuildByIdRequest) (*Guild, error)
	GetAllGuilds(context.Context, *GetAllGuildsRequest) (*GuildList, error)
	GetInvitations(context.Context, *GetGuildInvitationsRequest) (*GuildInvitationList, error)
	GetJoinRequests(context.Context, *GetGuildJoinRequestsRequest) (*GuildJoinRequestList, error)
	GetMemberRoles(context.Context, *GetGuildMemberRolesRequest) (*GuildMemberRoleList, error)
	GetMyGuild(context.Context, *GetMyGuildRequest) (*Guild, error)
	GetMyJoinRequests(context.Context, *GetMyJoinRequestsRequest) (*GuildJoinRequestList, error)
	mustEmbedUnimplementedGuildsServiceServer()
}

// UnimplementedGuildsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGuildsServiceServer struct{}

func (UnimplementedGuildsServiceServer) GetGuildById(context.Context, *GetGuildByIdRequest) (*Guild, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGuildById not implemented")
}
func (UnimplementedGuildsServiceServer) GetAllGuilds(context.Context, *GetAllGuildsRequest) (*GuildList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllGuilds not implemented")
}
func (UnimplementedGuildsServiceServer) GetInvitations(context.Context, *GetGuildInvitationsRequest) (*GuildInvitationList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInvitations not implemented")
}
func (UnimplementedGuildsServiceServer) GetJoinRequests(context.Context, *GetGuildJoinRequestsRequest) (*GuildJoinRequestList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJoinRequests not implemented")
}
func (UnimplementedGuildsServiceServer) GetMemberRoles(context.Context, *GetGuildMemberRolesRequest) (*GuildMemberRoleList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMemberRoles not implemented")
}
func (UnimplementedGuildsServiceServer) GetMyGuild(context.Context, *GetMyGuildRequest) (*Guild, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyGuild not implemented")
}
func (UnimplementedGuildsServiceServer) GetMyJoinRequests(context.Context, *GetMyJoinRequestsRequest) (*GuildJoinRequestList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyJoinRequests not implemented")
}
func (UnimplementedGuildsServiceServer) mustEmbedUnimplementedGuildsServiceServer() {}
func (UnimplementedGuildsServiceServer) testEmbeddedByValue()                       {}

// UnsafeGuildsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuildsServiceServer will
// result in compilation errors.
type UnsafeGuildsServiceServer interface {
	mustEmbedUnimplementedGuildsServiceServer()
}

func RegisterGuildsServiceServer(s grpc.ServiceRegistrar, srv GuildsServiceServer) {
	// If the following call pancis, it indicates UnimplementedGuildsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GuildsService_ServiceDesc, srv)
}

func _GuildsService_GetGuildById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGuildByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildsServiceServer).GetGuildById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildsService_GetGuildById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildsServiceServer).GetGuildById(ctx, req.(*GetGuildByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuildsService_GetAllGuilds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllGuildsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildsServiceServer).GetAllGuilds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildsService_GetAllGuilds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildsServiceServer).GetAllGuilds(ctx, req.(*GetAllGuildsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuildsService_GetInvitations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGuildInvitationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildsServiceServer).GetInvitations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildsService_GetInvitations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildsServiceServer).GetInvitations(ctx, req.(*GetGuildInvitationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuildsService_GetJoinRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGuildJoinRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildsServiceServer).GetJoinRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildsService_GetJoinRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildsServiceServer).GetJoinRequests(ctx, req.(*GetGuildJoinRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuildsService_GetMemberRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGuildMemberRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildsServiceServer).GetMemberRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildsService_GetMemberRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildsServiceServer).GetMemberRoles(ctx, req.(*GetGuildMemberRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuildsService_GetMyGuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyGuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildsServiceServer).GetMyGuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildsService_GetMyGuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildsServiceServer).GetMyGuild(ctx, req.(*GetMyGuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuildsService_GetMyJoinRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyJoinRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildsServiceServer).GetMyJoinRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildsService_GetMyJoinRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildsServiceServer).GetMyJoinRequests(ctx, req.(*GetMyJoinRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GuildsService_ServiceDesc is the grpc.ServiceDesc for GuildsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GuildsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.v1.GuildsService",
	HandlerType: (*GuildsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGuildById",
			Handler:    _GuildsService_GetGuildById_Handler,
		},
		{
			MethodName: "GetAllGuilds",
			Handler:    _GuildsService_GetAllGuilds_Handler,
		},
		{
			MethodName: "GetInvitations",
			Handler:    _GuildsService_GetInvitations_Handler,
		},
		{
			MethodName: "GetJoinRequests",
			Handler:    _GuildsService_GetJoinRequests_Handler,
		},
		{
			MethodName: "GetMemberRoles",
			Handler:    _GuildsService_GetMemberRoles_Handler,
		},
		{
			MethodName: "GetMyGuild",
			Handler:    _GuildsService_GetMyGuild_Handler,
		},
		{
			MethodName: "GetMyJoinRequests",
			Handler:    _GuildsService_GetMyJoinRequests_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
